source 'http://rubygems.org'

ruby '2.3.3'

gem 'carrierwave'
gem 'fog'
gem 'font-awesome-rails'
gem 'haml-rails'
gem 'jquery-rails'
gem 'less-rails'
gem 'sass-rails'
gem 'mini_magick'
gem 'pg'
gem 'rake'
gem 'rails', '~> 4.2.0'
gem 'sass'
gem 'therubyracer'
gem 'tinymce-rails'
gem 'twitter-bootstrap-rails', :git => 'https://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'will_paginate'
gem 'rails_12factor'
gem 'puma'

group :test, :development do
  gem 'hashie'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'awesome_print'
  gem 'timecop'
  gem 'factory_girl_rails'
end
