class ConvertAchievementsToFa < ActiveRecord::Migration
  def up
    execute "UPDATE achievements SET badge = 'fa fa-check' WHERE badge = 'icon-check'"
    execute "UPDATE achievements SET badge = 'fa fa-plus' WHERE badge = 'icon-plus'"
    execute "UPDATE achievements SET badge = 'fa fa-tags' WHERE badge = 'icon-tags'"
    execute "UPDATE achievements SET badge = 'fa fa-cogs' WHERE badge = 'icon-cogs'"
    execute "UPDATE achievements SET badge = 'fa fa-user' WHERE badge = 'icon-user'"
    execute "UPDATE achievements SET badge = 'fa fa-heart' WHERE badge = 'icon-heart'"
    execute "UPDATE achievements SET badge = 'fa fa-legal' WHERE badge = 'icon-legal'"
    execute "UPDATE achievements SET badge = 'fa fa-minus-circle' WHERE badge = 'icon-remove-circle'"
    execute "UPDATE achievements SET badge = 'fa fa-lemon-o' WHERE badge = 'icon-lemon'"
    execute "UPDATE achievements SET badge = 'fa fa-tag' WHERE badge = 'icon-tag'"
    execute "UPDATE achievements SET badge = 'fa fa-long-arrow-up' WHERE badge = 'icon-circle-arrow-up'"
    execute "UPDATE achievements SET badge = 'fa fa-adjust' WHERE badge = 'icon-adjust'"
    execute "UPDATE achievements SET badge = 'fa fa-trophy' WHERE badge = 'icon-trophy'"
    execute "UPDATE achievements SET badge = 'fa fa-magnet' WHERE badge = 'icon-magnet'"
    execute "UPDATE achievements SET badge = 'fa fa-camera' WHERE badge = 'icon-camera'"
    execute "UPDATE achievements SET badge = 'fa fa-lock' WHERE badge = 'icon-lock'"
    execute "UPDATE achievements SET badge = 'fa fa-fire' WHERE badge = 'icon-fire'"
    execute "UPDATE achievements SET badge = 'fa fa-clock-o' WHERE badge = 'icon-time'"
    execute "UPDATE achievements SET badge = 'fa fa-headphones' WHERE badge = 'icon-headphones'"
  end

  def down
    execute "UPDATE achievements SET badge = 'icon-check' WHERE badge = 'fa fa-check'"
    execute "UPDATE achievements SET badge = 'icon-plus' WHERE badge = 'fa fa-plus'"
    execute "UPDATE achievements SET badge = 'icon-tags' WHERE badge = 'fa fa-tags'"
    execute "UPDATE achievements SET badge = 'icon-cogs' WHERE badge = 'fa fa-cogs'"
    execute "UPDATE achievements SET badge = 'icon-user' WHERE badge = 'fa fa-user'"
    execute "UPDATE achievements SET badge = 'icon-heart' WHERE badge = 'fa fa-heart'"
    execute "UPDATE achievements SET badge = 'icon-legal' WHERE badge = 'fa fa-legal'"
    execute "UPDATE achievements SET badge = 'icon-remove-circle' WHERE badge = 'fa fa-minus-circle'"
    execute "UPDATE achievements SET badge = 'icon-lemon' WHERE badge = 'fa fa-lemon-o'"
    execute "UPDATE achievements SET badge = 'icon-tag' WHERE badge = 'fa fa-tag'"
    execute "UPDATE achievements SET badge = 'icon-adjust' WHERE badge = 'fa fa-adjust'"
    execute "UPDATE achievements SET badge = 'icon-trophy' WHERE badge = 'fa fa-trophy'"
    execute "UPDATE achievements SET badge = 'icon-magnet' WHERE badge = 'fa fa-magnet'"
    execute "UPDATE achievements SET badge = 'icon-camera' WHERE badge = 'fa fa-camera'"
    execute "UPDATE achievements SET badge = 'icon-lock' WHERE badge = 'fa fa-lock'"
    execute "UPDATE achievements SET badge = 'icon-fire' WHERE badge = 'fa fa-fire'"
    execute "UPDATE achievements SET badge = 'icon-time' WHERE badge = 'fa fa-clock-o'"
    execute "UPDATE achievements SET badge = 'icon-headphones' WHERE badge = 'fa fa-headphones'"
  end
end
